### ISSUE TITLE
CentOS Template doesn't install Cloud-init

### ISSUE THREAD

**Issue by Russell-IO** [lxc/lxc#1368]
Cloud-init doesn't work with CentOS 6, or 7.
And trying to install manually doesn't work (i.e.):
```
	lxc exec centos -- yum install -y cloud-utils cloud-init parted git
	lxc exec centos -- bash -c "echo 'datasource_list: [ NoCloud, ConfigDrive, OpenNebula, Azure, AltCloud, OVF, MAAS, GCE, OpenStack, CloudSigma, SmartOS, Ec2, CloudStack, None ]' > /etc/cloud/cloud.cfg.d/90_datastores.cfg"
	lxc exec centos -- init 6
```

N.B.: The lxd socket is functioning for metadata retrieval seems to be working well:
`curl --unix-socket /dev/lxd/sock http://169.254.169.254/1.0/config/user.user-data`
Results in pulling back the yaml user-data as expected
```
#cloud-config
users:
  - name: centos
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGRlmNKxYUbW6T4HD7VOZk4eKXrCO2FIPbj1zvjc19h9rD2C6zO+UIwvjqzwH5z4nLw2M8kdHFVBg39WPd9GXYbyQDVuIqqxvIoUg9K+zPeE42Bl7b4w6bLE3GD8YXNIdgKsbxo0/obdcwV/hrUEQKX60SREyDL9CRAfqxyOGwXpf2kNA==
runcmd:
  - yum install -y openssh-server
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers centos' /etc/ssh/sshd_config
  - restart ssh
  - locale-gen en_GB.UTF-8
```
