### ISSUE TITLE
Container with static IP does not autostart network

### ISSUE THREAD

**Issue by SwampFalc** [lxc/lxc#1405]
I have two containers, both setup for static IP networking.

One of them automatically starts their network when the container starts, the other doesn't, and I honestly don't see why or what's different.

## Host

/etc/network/interfaces
```
auto br3
iface br3 inet static
	address 10.0.0.229
	netmask 255.255.0.0
	gateway 10.0.1.254
	dns-nameservers 10.0.0.3
	bridge_ports eno3
	bridge_stp off
	bridge_fd 0
	bridge_maxwait 0
```

## Auto network OK

lxc config show:
```
name: puppetclient
profiles:
- br3
config:
  volatile.base_image: 683cdd3938706deeb66f19854ee27ef0c75e2594ce60ad4525357c3ce46f9772
  volatile.eth0.hwaddr: 00:16:3e:d3:a7:5f
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
```

/etc/network/interfaces:
```
auto eth0
iface eth0 inet static
  address 10.0.229.2
  netmask 255.255.0.0
  gateway 10.0.1.254
  dns-nameservers 10.0.0.3
```

## Auto network NOT OK

lxc config show:
```
name: puppetmaster
profiles:
- br3
config:
  volatile.base_image: 683cdd3938706deeb66f19854ee27ef0c75e2594ce60ad4525357c3ce46f9772
  volatile.eth0.hwaddr: 00:16:3e:86:75:c7
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
```

/etc/network/interfaces:
```
auth eth0
iface eth0 inet static
  address 10.0.229.1
  netmask 255.255.0.0
  gateway 10.0.1.254
  dns-nameservers 10.0.0.3
```

And this is the result after a full reboot of the host:
```
+--------------+---------+-------------------+------+------------+-----------+
|     NAME     |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-------------------+------+------------+-----------+
| puppetclient | RUNNING | 10.0.229.2 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-------------------+------+------------+-----------+
| puppetmaster | RUNNING |                   |      | PERSISTENT | 0         |
+--------------+---------+-------------------+------+------------+-----------+
```

`lxc exec puppetmaster ifup eth0` brings up the network, but after `lxc stop puppetmaster && lxc start puppetmaster` the network is down...
