### ISSUE TITLE
error: No root device could be found.

### ISSUE THREAD

**Issue by wiseflat** [lxc/lxc#1480]
Hi, 

I suddenly have a problem on my LXD infrastructure.
Today I tried to create containers based on my profile

```
ubuntu@mgmt1:~$ lxc launch ubuntu:16.04 -p portexploit toto
```
And the logs from journalctl :
```
mars 21 15:46:05 mgmt1 lxd[2955]: ephemeral=false lvl=eror msg="Failed creating container" name=toto t=2017-03-21T15:46:05+0000
```

The packages installed on my ubuntu server 16.10 :
```
ii  libgolang-gopkg-lxc-go-lxc.v2-1            0.0~git20161126.1.82a07a6-0ubuntu1~ubuntu16.10.1
ii  liblxc1                                    2.0.7-0ubuntu2~ubuntu16.10.1~ppa1
ii  lxc-common                                 2.0.7-0ubuntu2~ubuntu16.10.1~ppa1
ii  lxcfs                                      2.0.6-1~ubuntu16.10.1~ppa1
ii  lxd                                        2.12-0ubuntu1~ubuntu16.10.1~ppa1
ii  lxd-client                                 2.12-0ubuntu1~ubuntu16.10.1~ppa1
```

My infrastructure is based on 3 nodes with vxlan between them. I have the same behavior on each nodes.

And an example of my profile :

```
ubuntu@mgmt1:~$ lxc profile show portexploit
config: {}
description: portexploit profile
devices:
  eth0:
    nictype: macvlan
    parent: portexploit
    type: nic
name: portexploit
used_by:
- /1.0/containers/www
- /1.0/containers/aaa
- /1.0/containers/zzz
- /1.0/containers/xxx
```

What happened ? I don't have a clue...
Can someone tell me what's wrong ? and how to debug it ?
