### ISSUE TITLE
zfs storage pool doesn't show the proper block device name for "source" property

### ISSUE THREAD

**Issue by akadoya** [lxc/lxc#1743]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * Lxc version: 2.16

# Issue description

When creating a new zfs storage pool with the existing block device name, storage api creates a new zpool if it doesn't exist.
New zpool will be created on the block device specified by "source" property accurately, but the new lxc storage pool has zpool's pool name in its source property as well as in zfs.pool_name property.
Shouldn't this source property be consistent with the source that is passed through the command option? In this case, source should be the device name.

# Steps to reproduce

 1.  Create a new storage pool on the existing block device

```
# lxc storage create test_pool zfs source=/dev/sda5  zfs.pool_name=zpool_test
Storage pool test_pool created
```

 2. Step1 creates new zpool. 

```
# zpool status zpool_test
  pool: zpool_test
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	zpool_test  ONLINE       0     0     0
	  sda5      ONLINE       0     0     0

errors: No known data errors
```

 3. source property is showing the zpool name

```
# lxc storage show test_pool
config:
  source: zpool_test                          >>> this should be /dev/sda5
  zfs.pool_name: zpool_test
description: ""
name: test_pool
driver: zfs
used_by: []
```
