### ISSUE TITLE
ubuntu user = nobody inside the container

### ISSUE THREAD

**Issue by wiseflat** [lxc/lxc#1926]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04

# Issue description

Since I migrated containers to new and fresh host, I realized that my ubuntu user permissions inside the container changed. I made some changes on my lxc configuration, I did some tests as well (sharing storage from the host, I played with subuid/subgid, etc, dir/zfs, storage, etc)

# Information to attach

I am sure good eyes will see how I can fix that...
Could you tell me what are the right permissions to set both on host and container to fix it ?

## inside the container
```
ubuntu@wt-node-04:~$ lxc config show u1
architecture: x86_64
config:
  image.architecture: amd64
  image.build: "20170728_03:49"
  image.description: Ubuntu xenial (amd64) (20170728_03:49)
  image.distribution: ubuntu
  image.release: xenial
  volatile.base_image: 09c69deb97c721ebc74fb0e78d62c19b9ee180bc006c8704b64be998c0a32c75
  volatile.eth0.hwaddr: 00:16:3e:49:c1:7f
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- portdmz-m
```

```
root@u1:~# cat /etc/subuid
git:165536:65536
ubuntu:100000:65536

root@u1:~# cat /etc/subgid
git:165536:65536
ubuntu:100000:65536

root@u1:~# ll /home/
total 4
drwxr-xr-x  3 root   root     3 Jul 28 05:56 ./
drwxr-xr-x 21 root   root    21 Jul 28 05:55 ../
drwxr-xr-x  7 nobody nogroup 13 Oct  1 13:02 ubuntu/
```

## from the host
```
ubuntu@host-01:~$ ll /var/lib/lxd/storage-pools/default/containers/u1/rootfs/home/
total 4
drwxr-xr-x  3 100000 100000  3 Jul 28 05:56 ./
drwxr-xr-x 21 100000 100000 21 Jul 28 05:55 ../
drwxr-xr-x  7 ubuntu ubuntu 13 Oct  1 13:02 ubuntu/
```
