### ISSUE TITLE
LXC mounts /sys twice when running privileged container

### ISSUE THREAD

**Issue by tommyknows** [lxc/lxc#2602]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of
   * `lxc-start --version` seen in 3.3 and 2.21
   * `uname -a` 4.4.0-134

# Issue description
When starting a privileged container, `/sys` gets mounted twice. Once read-write, and once read-only.
```
root@test:~# mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
```

# Steps to reproduce

 1. Create a profile with `security.privileged`:
```
root@-lxc-1:~# lxc profile show test
config:
  security.privileged: "true"
description: Test Profile
devices:
  root:
    path: /
    pool: default
    type: disk
name: test
used_by:
- /1.0/containers/test
```

 2. Launch a container with that profile.
```
root@new-lxc-1:~# lxc launch images:ubuntu/16.04 test -p test
Creating test

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach

Starting test
```

 3. Exec into the container and check the mounts:
```
root@lxc-1:~# lxc exec test /bin/bash
root@test:~# mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
sysfs on /sys/devices/virtual/net type sysfs (rw,relatime)
sysfs on /sys/devices/virtual/net type sysfs (rw,nosuid,nodev,noexec,relatime)
```

Launching with Debug options:
[lxc.log](https://github.com/lxc/lxc/files/2369975/lxc.log)
