### ISSUE TITLE
bad lxc.mount.entry handling with musl C library

### ISSUE THREAD

**Issue by 5paceToast** [lxc/lxc#2798]
# Required information

 * Distribution: Alpine Linux
 * Distribution version: Edge
 * The output of "lxc info":
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    CENSORED
    -----END CERTIFICATE-----
  certificate_fingerprint: ee5abdc49ae2271ffb32984573cefbeff2d63e066efbac9d59f20c6ff5d409d6
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.19.17-0-vanilla
  server: lxd
  server_pid: 8642
  server_version: "3.9"
  storage: btrfs
  storage_version: 4.19.1
  server_clustered: false
  server_name: sauron
  project: default

```

# Issue description

1. Create a storage volume (`pkg`).
2. Attach the storage volume to two containers (`alfred` and `magni`).
3. Notice that modifying the path in one container does not influence the other.

I expected the storage to be shared.

Further investigation shows that the storage is not mounted whatsoever, so this bug is about that.

From what I've seen, the workflow for mounting storage containers under btrfs looks like so:
1. The volume is kept in `$LIBLXD/storage-pools/$POOL/custom/$VOLUME`
2. For containers that attach to it, it is mounted on `$LIBLXD/devices/$CONTAINER/$TYPE.$VOLUME.$MOUNT` (in this case, `alfred/disk.pkg.srv-pkg`)
3. Those are then mounted using lxd bindmounts; e.g `/var/log/lxd/alfred/lxc.conf` - `lxc.mount.entry = /var/lib/lxd/devices/alfred/disk.pkg.srv-pkg srv/pkg none bind,create=dir`

However, this mount never shows up inside the container.
For comparison, on an lvm-backed system at work (but still inside alpine), I can see: `/dev/lxd/custom_git on /var/lib/gitea type ext4 (rw,relatime,discard,stripe=32,data=ordered)`

## Additional Details

`/dev/lxd` only contains `sock` in both containers.
The same behavior is present in all of the following scenarios:
- Legacy cgroup layout in `/sys/fs/cgroup`
- Hybrid cgroup layout in `/sys/fs/cgroup`
- Unified cgroup layout in `/sys/fs/cgroup`
- LXCFS not running
- LXCFS running

To ensure that it's not some weird private namespacing, I also tried going directly into the container subvol and `touch`ing a file.
It appears inside of `disk.pkg.srv-pkg`, but not inside the container.

# Steps to reproduce

 1. Initialize storage (I have btrfs, non-loop).
 2. Create a custom storage volume,
 3. Attach it to a container.
 4. Notice that the container does not have it mounted.

# Information to attach

 - [x] Any relevant kernel output (`dmesg`): nothing relevant
 - [x] Container log (`lxc info NAME --show-log`):
```
Name: alfred
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/01/25 12:59 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 7899
Ips:
  eth0: inet    192.168.0.10    vethR72M3L
  eth0: inet6   fe80::216:3eff:fe73:5ace        vethR72M3L
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 1
  Network usage:
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    eth0:
      Bytes received: 338.30kB
      Bytes sent: 1.73kB
      Packets received: 1161
      Packets sent: 16

Log:

lxc alfred 20190125140102.698 WARN     initutils - initutils.c:setproctitle:324 - Invalid argument - Failed to set cmdline
lxc alfred 20190125140102.911 WARN     conf - conf.c:lxc_setup_devpts:1641 - Invalid argument - Failed to unmount old devpts instance
```
 - [x] Container configuration (`lxc config show NAME --expanded`):
```
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: Alpine edge amd64 (20190125_13:01)
  image.os: Alpine
  image.release: edge
  image.serial: "20190125_13:01"
  volatile.base_image: 7e688b0efe698e4ae3a03d71c579e9f7d36a897e6f47c1c5959d525843363ffd
  volatile.eth0.hwaddr: 00:16:3e:73:5a:ce
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  pkg:
    path: /srv/pkg
    pool: default
    source: pkg
    type: disk
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log): Empty
 - [x] Output of the client with --debug: N/A - issue inside container
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue):
```
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 85b6b4e1-3cb0-4f86-b056-2a2ac123240c'
timestamp: "2019-01-25T14:19:38.186655391Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:39.749688641Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/alfred
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:39.753085459Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New event listener: 108ee60e-e988-4005-bb09-0173fc332e51'
timestamp: "2019-01-25T14:19:39.75817152Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events?project=
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:39.758075581Z"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/alfred/state
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:39.759363734Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 208d33e3-0caf-43e8-95b6-be7ec9ffb3b9'
timestamp: "2019-01-25T14:19:39.839889847Z"
type: logging


metadata:
  class: task
  created_at: "2019-01-25T14:19:39.762645525Z"
  description: Starting container
  err: ""
  id: 208d33e3-0caf-43e8-95b6-be7ec9ffb3b9
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/alfred
  status: Pending
  status_code: 105
  updated_at: "2019-01-25T14:19:39.762645525Z"
timestamp: "2019-01-25T14:19:39.839955569Z"
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 208d33e3-0caf-43e8-95b6-be7ec9ffb3b9'
timestamp: "2019-01-25T14:19:39.839993647Z"
type: logging


metadata:
  class: task
  created_at: "2019-01-25T14:19:39.762645525Z"
  description: Starting container
  err: ""
  id: 208d33e3-0caf-43e8-95b6-be7ec9ffb3b9
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/alfred
  status: Running
  status_code: 103
  updated_at: "2019-01-25T14:19:39.762645525Z"
timestamp: "2019-01-25T14:19:39.840026672Z"
type: operation


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/208d33e3-0caf-43e8-95b6-be7ec9ffb3b9
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:39.841797605Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/alfred
timestamp: "2019-01-25T14:19:39.920046193Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-01-25T14:19:39.998242964Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume "pkg" on storage pool "default"
timestamp: "2019-01-25T14:19:39.998216157Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume "pkg" on storage pool "default"
timestamp: "2019-01-25T14:19:39.998458651Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-01-25T14:19:39.998779884Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "alfred" on storage pool "default"
timestamp: "2019-01-25T14:19:39.99874818Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "alfred" on storage pool "default"
timestamp: "2019-01-25T14:19:39.998977652Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-01-25T14:19:40.07328537Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "alfred" on storage pool "default"
timestamp: "2019-01-25T14:19:40.073253338Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "alfred" on storage pool "default"
timestamp: "2019-01-25T14:19:40.073494582Z"
type: logging


metadata:
  context:
    action: start
    created: 2019-01-25 12:59:17.453551608 +0000 UTC
    ephemeral: "false"
    name: alfred
    project: default
    stateful: "false"
    used: 2019-01-25 14:19:25.331141501 +0000 UTC
  level: info
  message: Starting container
timestamp: "2019-01-25T14:19:40.073547576Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:40.116268618Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/7/onstart
  level: dbug
  message: handling
timestamp: "2019-01-25T14:19:40.119298416Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-01-25T14:19:40.124754221Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "alfred" on storage pool "default"
timestamp: "2019-01-25T14:19:40.124722655Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "alfred" on storage pool "default"
timestamp: "2019-01-25T14:19:40.12498747Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Success for task operation: 208d33e3-0caf-43e8-95b6-be7ec9ffb3b9'
timestamp: "2019-01-25T14:19:40.317283579Z"
type: logging


metadata:
  action: container-started
  source: /1.0/containers/alfred
timestamp: "2019-01-25T14:19:40.317252107Z"
type: lifecycle


metadata:
  context:
    action: start
    created: 2019-01-25 12:59:17.453551608 +0000 UTC
    ephemeral: "false"
    name: alfred
    project: default
    stateful: "false"
    used: 2019-01-25 14:19:25.331141501 +0000 UTC
  level: info
  message: Started container
timestamp: "2019-01-25T14:19:40.317209383Z"
type: logging


metadata:
  class: task
  created_at: "2019-01-25T14:19:39.762645525Z"
  description: Starting container
  err: ""
  id: 208d33e3-0caf-43e8-95b6-be7ec9ffb3b9
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/alfred
  status: Success
  status_code: 200
  updated_at: "2019-01-25T14:19:39.762645525Z"
timestamp: "2019-01-25T14:19:40.31734122Z"
type: operation
```
