### ISSUE TITLE
After upgrade: Failed to move network device “wlan0” to network namespace: Operation not permitted

### ISSUE THREAD

**Issue by marcialvieira** [lxc/lxc#3105]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
   * Kernel version: 4.18.0-25-generic
   * LXD version: 3.15
   * Storage backend in use: btrfs

# Issue description

After lxd snap auto-refresh, the problem occurred.

```
lxc firewall 20190725200021.783 ERROR    start - start.c:proc_pidfd_open:1644 - Function not implemented - Failed to send signal through pidfd
lxc firewall 20190725200021.900 ERROR    network - network.c:lxc_network_move_created_netdev_priv:3292 - Operation not permitted - Failed to move network device "wlp3s0" with ifindex 3 to network namespace 25846
lxc firewall 20190725200021.900 ERROR    start - start.c:lxc_spawn:1846 - Failed to create the network
lxc firewall 20190725200021.900 WARN     network - network.c:lxc_delete_network_priv:3374 - Failed to rename interface with index 2 from "enp2s0" to its initial name "enp2s0"
lxc firewall 20190725200021.960 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "ABORTING" instead of "RUNNING"
lxc firewall 20190725200021.961 ERROR    start - start.c:__lxc_start:2036 - Failed to spawn container "firewall"
lxc 20190725200022.408 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"
```

The only solution was to revert.

```
# snap changes
ID   Status  Spawn               Ready               Summary
18   Done    today at 14:45 -03  today at 14:45 -03  Auto-refresh snap "lxd"
19   Done    today at 17:15 -03  today at 17:15 -03  Revert "lxd" snap
#

**Comment by stgraber** [comment]
@marcialvieira can you show `lxc config show --expanded NAME` for that container.

**Comment by stgraber** [comment]
@brauner I wonder if some of the refactoring/changes in the network code that you did or the changes that @tomponline did might have broken the wlan/80211 logic that we have in liblxc to track down the phy and move that to the netns.

**Comment by brauner** [comment]
Moving wlan devices has - afaict - never really worked and is also dependent on the driver used. But let's see what info we get.

**Comment by marcialvieira** [comment]
> @marcialvieira can you show `lxc config show --expanded NAME` for that container.

```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20190627.1)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20190627.1"
  image.version: "18.04"
  volatile.base_image: 6ae1c6e92017402f1aee655fa8d785ee9d2337a3369d76115cecad5e7a303e07
  volatile.enp2s0.last_state.created: "false"
  volatile.enp2s0.last_state.hwaddr: xx:xx:xx:xx:xx:xx
  volatile.enp2s0.last_state.mtu: "1500"
  volatile.eth1.host_name: veth5A1V8F
  volatile.eth1.hwaddr: xx:xx:xx:xx:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.wlp3s0.last_state.created: "false"
  volatile.wlp3s0.last_state.hwaddr: xx:xx:xx:xx:xx:xx
  volatile.wlp3s0.last_state.mtu: "1500"
devices:
  enp2s0:
    name: enp2s0
    nictype: physical
    parent: enp2s0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: vg0-lxd
    type: disk
  wlp3s0:
    name: wlp3s0
    nictype: physical
    parent: wlp3s0
    type: nic
ephemeral: false
profiles:
- nonet
stateful: false
description: ""
```
