### ISSUE TITLE
LXC container network does not work with host bridge

### ISSUE THREAD

**Issue by a-hahn** [lxc/lxc#3547]
* Distribution: Ubuntu 18.04 LTS
 * Distribution version: 18.04
 * The output of
   * `lxc-start --version` 3.03
   * `lxc-checkconfig`
```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.15.0-118-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/rdma
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/pids

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```
   * `uname -a`  Linux ubuntu90 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`

```
12:pids:/user.slice/user-1000.slice/session-3.scope
11:blkio:/user.slice
10:freezer:/
9:hugetlb:/
8:rdma:/
7:cpuset:/
6:perf_event:/
5:cpu,cpuacct:/user.slice
4:net_cls,net_prio:/
3:devices:/user.slice
2:memory:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-3.scope
0::/user.slice/user-1000.slice/session-3.scope
```
   * `cat /proc/1/mounts`
```
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8148444k,nr_inodes=2037111,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1642580k,mode=755 0 0
/dev/sda2 / ext4 rw,relatime,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
--- and lots of overlays probably from a microk8s installation ---
```

# Issue description

I tried to achieve that my containers get an IP from the local router and are accessible from the local net. This worked well when using a physical host interface and macvlan config for the containers **except** the containers where not reachable from the host. Following advices on the internet I tried to add a bridge to the host and configured that bridge as a parent for the containers.
However that does not work, the containers do not see this bridge. See the last item ``lxc list`` containers have no ip attached.

A brief description of what failed or what could be improved.

# Steps to reproduce

1) cat /etc/netplan/50-cloud-init.yaml
```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s10:
            dhcp4: false
    bridges:
      br0:
        dhcp4: yes
        interfaces: [enp0s10]
```

2) lxd init
```
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: n
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: n
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: y
Name of the existing bridge or host interface: br0
Would you like LXD to be available over the network? (yes/no) [default=no]: n
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: y
config: {}
networks: []
storage_pools: []
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: br0
      type: nic
  name: default
cluster: null
```

3) Ouput of ip -a
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether 00:26:2d:2d:2f:2f brd ff:ff:ff:ff:ff:ff
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:d1:f8:c7:9d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d1ff:fef8:c79d/64 scope link 
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 76:e2:42:66:de:7a brd ff:ff:ff:ff:ff:ff
    inet 10.1.88.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::74e2:42ff:fe66:de7a/64 scope link 
       valid_lft forever preferred_lft forever
6: vethd71fdf1@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 7a:f1:63:33:62:0e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::78f1:63ff:fe33:620e/64 scope link 
       valid_lft forever preferred_lft forever
8: vetha8e1bad@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether ea:80:02:98:26:aa brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::e880:2ff:fe98:26aa/64 scope link 
       valid_lft forever preferred_lft forever
9: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 52:94:ba:7b:35:56 brd ff:ff:ff:ff:ff:ff
    inet 10.1.88.1/24 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::5094:baff:fe7b:3556/64 scope link 
       valid_lft forever preferred_lft forever
28: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b6:ba:18:24:cd:d3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.90/16 brd 192.168.255.255 scope global dynamic br0
       valid_lft 84562sec preferred_lft 84562sec
    inet6 fe80::b4ba:18ff:fe24:cdd3/64 scope link 
       valid_lft forever preferred_lft forever
--- some veth.... interface not shown
```

4) Output of ls /sys/class/net -l
```
total 0
lrwxrwxrwx 1 root root 0 Oct  9 09:48 br0 -> ../../devices/virtual/net/br0
lrwxrwxrwx 1 root root 0 Oct  9 09:41 cni0 -> ../../devices/virtual/net/cni0
lrwxrwxrwx 1 root root 0 Oct  9 09:41 docker0 -> ../../devices/virtual/net/docker0
lrwxrwxrwx 1 root root 0 Oct  9 09:41 enp0s10 -> ../../devices/pci0000:00/0000:00:0a.0/net/enp0s10
lrwxrwxrwx 1 root root 0 Oct  9 09:41 flannel.1 -> ../../devices/virtual/net/flannel.1
lrwxrwxrwx 1 root root 0 Oct  9 09:41 lo -> ../../devices/virtual/net/lo
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth026a9a44 -> ../../devices/virtual/net/veth026a9a44
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth0e44369d -> ../../devices/virtual/net/veth0e44369d
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth13e5590f -> ../../devices/virtual/net/veth13e5590f
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth274a64ca -> ../../devices/virtual/net/veth274a64ca
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth2978ab12 -> ../../devices/virtual/net/veth2978ab12
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth3af928be -> ../../devices/virtual/net/veth3af928be
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth3b3f3ede -> ../../devices/virtual/net/veth3b3f3ede
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth3d55b9a7 -> ../../devices/virtual/net/veth3d55b9a7
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth462d275d -> ../../devices/virtual/net/veth462d275d
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth523fd240 -> ../../devices/virtual/net/veth523fd240
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth5a908a26 -> ../../devices/virtual/net/veth5a908a26
lrwxrwxrwx 1 root root 0 Oct  9 10:18 veth71G2SW -> ../../devices/virtual/net/veth71G2SW
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth97dc0871 -> ../../devices/virtual/net/veth97dc0871
lrwxrwxrwx 1 root root 0 Oct  9 09:48 veth9cd43aa7 -> ../../devices/virtual/net/veth9cd43aa7
lrwxrwxrwx 1 root root 0 Oct  9 09:48 vetha27ebd96 -> ../../devices/virtual/net/vetha27ebd96
lrwxrwxrwx 1 root root 0 Oct  9 09:48 vetha5fa199e -> ../../devices/virtual/net/vetha5fa199e
lrwxrwxrwx 1 root root 0 Oct  9 09:41 vetha8e1bad -> ../../devices/virtual/net/vetha8e1bad
lrwxrwxrwx 1 root root 0 Oct  9 09:48 vethc0be0451 -> ../../devices/virtual/net/vethc0be0451
lrwxrwxrwx 1 root root 0 Oct  9 09:41 vethd71fdf1 -> ../../devices/virtual/net/vethd71fdf1
lrwxrwxrwx 1 root root 0 Oct  9 09:48 vethdb9563ff -> ../../devices/virtual/net/vethdb9563ff
lrwxrwxrwx 1 root root 0 Oct  9 09:48 vethe7ed723a -> ../../devices/virtual/net/vethe7ed723a
lrwxrwxrwx 1 root root 0 Oct  9 09:48 vethfbe629d8 -> ../../devices/virtual/net/vethfbe629d8
```
5) lxc profile show default
```
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/ubuntu1
- /1.0/containers/ubuntu2
```

6) Launch container
```
lxc launch ubuntu:20.04 ubuntu1
```

7) show container config: ``lxc config show ubuntu1``
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200921.1)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200921.1"
  image.version: "20.04"
  volatile.base_image: 4746a4889a31e449e6c5e2764eb733a60e85131be3165c91d5f5a8346f0ba43c
  volatile.eth0.hwaddr: 00:16:3e:e4:44:1e
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

7) lxc list
```
+---------+---------+------+------+------------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+---------+---------+------+------+------------+-----------+
| ubuntu1 | RUNNING |      |      | PERSISTENT | 0         |
+---------+---------+------+------+------------+-----------+
| ubuntu2 | STOPPED |      |      | PERSISTENT | 0         |
+---------+---------+------+------+------------+-----------+

```
