### ISSUE TITLE
network acls order

### ISSUE THREAD

**Issue by TorbenMartin** [lxc/lxc#4505]
hello.

LXD -> ubuntu 24.04 VM -> INCUS -> VM1/VM2

VM1 = 10.194.74.1/24 (hjbvhjj)
VM2 = 10.30.208.1/24 (qqq)

i want set allow rule before drop rule.

how is that possible?

`root@above-whippet:~# nft list rulese`

```
        chain acl.qqq {
                ct state established,related accept
                iifname "qqq" ip daddr 10.194.74.0/24 drop
                iifname "qqq" ip daddr 10.194.74.44 accept
                iifname "qqq" accept
                oifname "qqq" reject
        }

```

network rule "default"

```
name: default
description: ""
egress:
- action: allow
  destination: 10.194.74.44
  state: enabled
ingress: []
config: {}
used_by:
- /1.0/networks/qqq
project: default
```

```
name: default2
description: ""
egress:
- action: drop
  destination: 10.194.74.0/24
  state: enabled
ingress: []
config: {}
used_by:
- /1.0/networks/qqq
project: default
```

`incus network set qqq security.acls="default,default2"`

![Bildschirmfoto zu 2024-12-17 13-05-28](https://github.com/user-attachments/assets/410b25a4-b57d-41a6-a821-b618cb3daef2)
![Bildschirmfoto zu 2024-12-17 13-05-10](https://github.com/user-attachments/assets/964fb791-c47d-4979-90f8-cf4f22615d27)
